#!/usr/bin/env ruby
#
# This is a simple script to create usable ruby files.

if ARGV.length == 0
  puts "Usage: mkruby {filename [filename ...]}."
  exit (1)
end

for i in 0..ARGV.length-1
  filename = ARGV[i].to_s
  if filename =~ /.*(.rb)/
    `echo '#!/usr/bin/env ruby' > #{filename}`
    `chmod 744 ./#{filename}`
  else
    `echo '#!/usr/bin/env ruby' > #{filename}.rb`
    `chmod 744 ./#{filename}.rb`
  end
end
